[Data]
adj_filename = ../../../../data/smoke/CHAP/fixed_0.2/channel_0/grid_edges.csv
graph_signal_matrix_filename = ../../../../data/smoke/CHAP/fixed_0.2/channel_0
miss_rate = 0.2
miss_type = fixed
num_of_vertices = 1024
points_per_hour = 7
num_for_predict = 7
len_input = 7
dataset_name = CHAP

[Training]
batch_size = 1
model_name = GCASTN
num_of_weeks = 0
num_of_days = 0
num_of_hours = 1
start_epoch = 0
epochs = 1
fine_tune_epochs = 0
learning_rate = 0.001
direction = 2
encoder_input_size = 1
decoder_input_size = 1
dropout = 0.0
kernel_size = 3
num_layers = 4
d_model = 64
nb_head = 4
scaledsat = 1
se = 1
smooth_layer_num = 0
aware_temporal_context = 1
te = 1

