[prepare]
seq_len = 7
attributes = 1
fill_value = 0
test_ratio = 0.09847094801223241
val_ratio = 0.09847094801223241
miss_rate = 0.8
type = fixed
file_prefix = ./training_data/CHAP_fixed_0.8_channel_0
ori_file_prefix = ../data/adapted/CHAP/fixed_0.8/channel_0

