[prepare]
seq_len = 7
attributes = 1
fill_value = 0
test_ratio = 0.09847094801223241
val_ratio = 0.09847094801223241
miss_rate = 0.6
type = random
file_prefix = ./training_data/CHAP_random_0.6_channel_0
ori_file_prefix = ../data/adapted/CHAP/random_0.6/channel_0

