[file]
save_prefix = ./experiments/CHAP_fixed_0.4_channel_0
data_prefix = ../data/adapted/CHAP/fixed_0.4/channel_0/split

[train]
miss_rate = 0.4
type = fixed
cuda = 0
use_nni = 0
test_ratio = 0.2
val_ratio = 0.2
sample_len = 7
epoch = 100
pretrain_epoch = 5
disc_iters = 7
learning_rate = 0.001
batch_size = 16
patience = 4
alpha = 100
z_dim = 64
h_dim = 64
val_epoch = 5

