[train]
use_nni = 0
learning_rate = 0.001
epochs = 100
batch_size = 32
model = brits_new
hid_size = 128
cuda = 0
miss_rate = 0.2
type = fixed
nodes = 1024
seq_len = 12
attributes = 1
patience = 10
file_prefix = ./training_data/TaxiBJ_fixed_0.2_channel_0
experiment_path = ./experiments/TaxiBJ_fixed_0.2_channel_0
val_epoch = 2

