[file]
data_prefix = ../data/smoke/CHAP/fixed_0.2/channel_0

[train]
miss_rate = 0.2
type = fixed
epochs = 1
batch_size = 1
lr = 0.0001
use_nni = 0
test_ratio = 0.2
val_ratio = 0.2
sample_len = 7

[diffusion]
layers = 4
channels = 64
nheads = 8
diffusion_embedding_dim = 64
beta_start = 0.0001
beta_end = 0.5
num_steps = 100
nsample = 10
schedule = quad

[model]
timeemb = 128
featureemb = 16
target_strategy = mix

