[Data]
adj_filename = ../data/adapted/BikeNYC/random_0.4/channel_0/grid_edges.csv
graph_signal_matrix_filename = ../data/adapted/BikeNYC/random_0.4/channel_0
miss_rate = 0.4
miss_type = random
num_of_vertices = 288
points_per_hour = 12
num_for_predict = 12
len_input = 12
dataset_name = BikeNYC
train_ratio = 0.6990424076607387
val_ratio = 0.09986320109439124
test_ratio = 0.20109439124487005

[Training]
use_nni = 0
batch_size = 4
model_name = ASTGNN
num_of_weeks = 0
num_of_days = 0
num_of_hours = 1
start_epoch = 0
epochs = 80
fine_tune_epochs = 20
learning_rate = 0.001
direction = 2
encoder_input_size = 1
decoder_input_size = 1
dropout = 0.0
kernel_size = 3
num_layers = 4
d_model = 64
nb_head = 8
scaledsat = 1
se = 1
smooth_layer_num = 0
aware_temporal_context = 1
te = 1
val_epoch = 10

