[prepare]
seq_len = 12
attributes = 1
fill_value = 0
test_ratio = 0.2
val_ratio = 0.1
miss_rate = 0.2
type = fixed
file_prefix = ./smoke_data/BikeNYC_fixed_0.2
ori_file_prefix = ../data/smoke/BikeNYC/fixed_0.2/channel_0

